// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/control-room/ControlRoom.tsx": () => import("../components/mockups/control-room/ControlRoom.tsx"),
  "./components/mockups/control-room/FieldCrewCheckIn.tsx": () => import("../components/mockups/control-room/FieldCrewCheckIn.tsx"),
  "./components/mockups/control-room/PortfolioComparison.tsx": () => import("../components/mockups/control-room/PortfolioComparison.tsx"),
  "./components/mockups/obra-control/ObraControlCommandCenter.tsx": () => import("../components/mockups/obra-control/ObraControlCommandCenter.tsx"),
  "./components/mockups/obra-control/ObraControlPolished.tsx": () => import("../components/mockups/obra-control/ObraControlPolished.tsx"),
  "./components/mockups/obra-control/ObraControlPortfolio.tsx": () => import("../components/mockups/obra-control/ObraControlPortfolio.tsx"),
  "./components/mockups/obra-control/ObraControlWarmDesk.tsx": () => import("../components/mockups/obra-control/ObraControlWarmDesk.tsx"),
  "./components/mockups/obra-control/PortfolioSplit.tsx": () => import("../components/mockups/obra-control/PortfolioSplit.tsx")
};
